# Site settings
title: smith.place
email: tim@smith.place
description: > # this means to ignore newlines until "baseurl:"
  The Internet home of the Smith family. (One of them, anyway.)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://smith.place" # the base hostname & protocol for your site

# Build settings
# markdown: kramdown
